services:
  - type: web
    name: b2bop-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn b2bop_project.wsgi
    runtime: python
    region: oregon  # or frankfurt, singapore, etc.
    plan: free
    branch: main  # change this if your branch is different
    autoDeploy: true

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: b2bop_project.settings  # adjust if needed
      - key: SECRET_KEY
        value: django-insecure-g56qefvrrgnx_ygpsz-#!ao71tv@!fjk49mukq68@lh#p*6%t+'
      - key: DEBUG
        value: "False"
      - key: MAILGUN_API_KEY
        value: ${MAILGUN_API_KEY}  # if using secrets from dashboard
      - key: MAILGUN_DOMAIN
        value: ${MAILGUN_DOMAIN}
      - key: SENDGRID_API_KEY
        value: ${SENDGRID_API_KEY}
